### PR TITLE
Fix BoundsError

### LINKED ISSUE #3: BoundsError for several datafiles
Heartbeat detection does not work for several datasets, because of BoundsError

The error occurs, if `searchback_index == 1` in  https://github.com/cbrnr/HeartBeats.jl/blob/a87e742604b8174729361d8a9489d22d08628459/src/HeartBeats.jl#L79

### PR DESCRIPTION
**Pull request by lindemann09**
Fixes #3.

### CODE REVIEW

**Comment by cbrnr** [comment]
Thanks for the PR! This might be an off-by-one error though, because I basically copied the code from Python, see here:

https://github.com/cbrnr/sleepecg/blob/main/src/sleepecg/heartbeats.py#L449

So instead of adding an additional constraint, I think it would be good to try to stay as closely as possible to the Python implementation. Unless of course that implementation also suffers from the issue you are having with some of your datasets. Could you perhaps try and see if the Python implementation works for you?

**Comment by lindemann09** [comment]
The bug occurs unfortunately frequently, if you process only  short periods of ecg recordings.

 The Python implementation works, because  `searchback_index` is always ` >= 1`.  Thus, [`array[searchback_index-1]`](https://github.com/cbrnr/sleepecg/blob/056a9358f4fe0147d1088498723255ac9bea4a30/src/sleepecg/heartbeats.py#L453C36-L453C70) does not cause this an error. 

In Julia, however, indexing starts with 1 and not 0.

**Comment by lindemann09** [comment]
If you want to stay as close as possible to the Python implementation, you need to ensure in Julia at least that `searchback_index`  never starts searching with a value `< 2`, because line [453]( https://github.com/cbrnr/sleepecg/blob/056a9358f4fe0147d1088498723255ac9bea4a30/src/sleepecg/heartbeats.py#L453C36-L453C70)  

See here my updated pull request to make your script running with all data.   

```
searchback_index = best_searchback_index < 2 ? 2 : best_searchback_index
```

**Comment by cbrnr** [comment]
Yes, the reason is definitely an error due to Julia being 1-indexed. However, I'm not sure if limiting the index like this is the best solution. Would not changing [lines 53-54](https://github.com/cbrnr/HeartBeats.jl/blob/main/src/HeartBeats.jl#L53-L54)

```julia
    peak_index = -refractory_samples + 1
    previous_peak_index = -refractory_samples + 1
```

to

```julia
    peak_index = -refractory_samples + 2
    previous_peak_index = -refractory_samples + 2
```

perhaps also solve the issue? The `+ 1` is directly taken from Python, so given that this represents an index computation, I think it should be adjusted to `+ 2`.

**Comment by lindemann09** [comment]
Yes, that fixes the issue as well and, I agree, it's the best solution. I changed my pull request accordingly. 

Thanks a lot and sorry, for my late response.

**Comment by cbrnr** [comment]
Great! I would like to separate PRs from releases though, so could you please rebase, remove the version bump, and add a changelog entry in `CHANGELOG.md` under the `[UNRELEASED]` section? Something like

```
### Fixed
Fix off-by-one index error in `searchback_index` ([#4](https://github.com/cbrnr/HeartBeats.jl/pull/4) by [Oliver Lindemann](https://github.com/lindemann09))
```

Once this PR is merged I'll cut a new release.

**Comment by lindemann09** [comment]
I removed the version bump and updated the  `CHANGELOG.md`.

**Comment by cbrnr** [comment]
Thanks @lindemann09! I'll make a new release soon!

**Pull request merged**
